### ISSUE TITLE
Still says "Connecting to Spotify"

### ISSUE THREAD

**Issue by jettcrowson** [tma02/spotispy#21] opened 2017-07-20 20:46 UTC
Even after the last update, it won't show the album

**Comment by NutritiousCookie** [comment] 2017-07-30 20:28
Same issue here. Is this the same issue from May, or did Spotify break itself again?

**Comment by tma02** [comment] 2017-08-02 06:01
I believe this is a duplicate of #18.

**Closed by tma02** 2017-08-02 06:01 UTC
