### ISSUE TITLE
Not connecting to spotify

### ISSUE THREAD

**Issue by WerWolv98** [tma02/spotispy#19] opened 2017-07-07 19:35 UTC
When SpotiSpy is started and Spotify runs in the background it finds it and tries to connect to it. It finds the artist and the song name but can't find the album art. 

This is the error message I get when using spotispy.exe /K:

enumerated 3 displays.
waiting for spotify...
4370
{ version: 9,
  client_version: '1.0.58.573.g57c9cd87',
  running: true }
4370
ready to grab album art.
found new song title.
song title: Something Just Like This
[TypeError: Cannot read property '0' of undefined]

**Comment by tma02** [comment] 2017-07-07 21:42
Sounds like a duplicate of #18. Will close this unless something suggests it's not actually a duplicate issue.

**Closed by tma02** 2017-07-07 21:42 UTC
